version: '2'
services:
  dbclient:
    image: postgres:9.6
    container_name: hackathon_db
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - "./backups:/backups"
