version: '2'
services:
  db:
    expose:
      - '5432' 
  frontend:
    image: node:7.7
    working_dir: /frontend
    command: npm run start
    volumes:
      - ./frontend:/frontend
    ports:
      - '3000:3000'
