version: '2'
services:
  db:
    expose:
      - '5432' 
  frontend:
    image: node:7.7
    working_dir: /frontend
    command: npm run start
    volumes:
      - ./frontend:/frontend
    ports:
      - '3000:3000'
  backend:
    image: billyteves/alpine-golang-glide
    working_dir: /go/src/github.com/Rademade/hackathon-machine/backend
    command: /bin/bash -c "go run migrate.go && go run server.go"
    volumes:
      - ./backend:/go/src/github.com/Rademade/hackathon-machine/backend
    ports:
      - "1323:1323"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - db
