version: '2'
services:
  db:
    expose:
      - '5432' 
  frontend:
    image: node:7.7
    working_dir: /frontend
    command: npm run start
    volumes:
      - ./frontend:/frontend
    ports:
      - '3000:3000'
  backend:
    image: golang:1.7
    working_dir: /backend
    command: go run server.go
    volumes:
      - ./backend:/backend
    ports:
      - "8000:1323"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - db
